# Non-Communicable Disease Burden (NCD)

```{r}
# Load necessary packages
pacman::p_load(tidyverse, knitr, here)

# Import the non-communicable diseases data
data_ncd <- read_csv(here("data/burden-of-disease-ncd.csv"))
```

```{r}
# Filter the dataset to include only the three countries chosen by your group.
data_ncd_mini <- data_ncd %>% 
  filter(Entity %in% c("Latvia", "Laos", "Jamaica")) %>% 
  select(-Code)
data_ncd_mini
```

## Table of Estimates for NCD Burden Over Time

```{r}
# Here render a table for the DALY burden over time for the three countries. 
# You should pivot the data wider to show each country in a separate column.
data_ncd_wide <- data_ncd_mini %>% 
  pivot_wider(names_from = Entity,
              values_from = `DALYs (Disability-Adjusted Life Years) - Communicable, maternal, neonatal, and nutritional diseases - Sex: Both - Age: Age-standardized (Rate)`)
# Use kable() from the knitr package to render the table.
kable(data_ncd_wide)
```

## Plot Showing Trends in NCD Burden Over Time

```{r}
# Here, plot a line graph showing the trend of DALY burden for the chosen countries over time. You can use ggplot2 to create this plot. Each country's line should be a different color.
# NOTE: Use your long 'mini' data frame for plotting, not the wide data used for the table. 
plot_2 <- data_ncd_mini %>% 
  ggplot(aes(x=Year,
             y=`DALYs (Disability-Adjusted Life Years) - Communicable, maternal, neonatal, and nutritional diseases - Sex: Both - Age: Age-standardized (Rate)`,
             colour = Entity)) +
  geom_line(size = 0.6) +
  labs(x = "Year",
       y = "DALYs Lost",
       title = "Trends in NCD Burden Over Time")
plot_1
```

## Summary of NCD Burden Findings

Provide a brief analysis based on the data presented in the table and chart. Highlight any significant findings or patterns. About 3 sentences.
